// Auto-generated by: pnpm supabase gen types typescript --project-id <YOUR_PROJECT_ID> > src/types/database.ts
// Replace this file with the actual generated output after setting up your Supabase project.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          display_name: string;
          avatar_url: string | null;
          role: "admin" | "anfitrion" | "participante";
          verified_lldm: boolean;
          bio: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name: string;
          avatar_url?: string | null;
          role?: "admin" | "anfitrion" | "participante";
          verified_lldm?: boolean;
          bio?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          display_name?: string;
          avatar_url?: string | null;
          role?: "admin" | "anfitrion" | "participante";
          verified_lldm?: boolean;
          bio?: string | null;
          updated_at?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          icon: string | null;
          order_index: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          icon?: string | null;
          order_index?: number;
          created_at?: string;
        };
        Update: {
          name?: string;
          slug?: string;
          description?: string | null;
          icon?: string | null;
          order_index?: number;
        };
      };
      platikas: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          host_id: string;
          status: "scheduled" | "live" | "ended";
          livekit_room_name: string | null;
          radio_output_active: boolean;
          thumbnail_url: string | null;
          scheduled_at: string | null;
          started_at: string | null;
          ended_at: string | null;
          recording_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          host_id: string;
          status?: "scheduled" | "live" | "ended";
          livekit_room_name?: string | null;
          radio_output_active?: boolean;
          thumbnail_url?: string | null;
          scheduled_at?: string | null;
          started_at?: string | null;
          ended_at?: string | null;
          recording_url?: string | null;
          created_at?: string;
        };
        Update: {
          title?: string;
          description?: string | null;
          status?: "scheduled" | "live" | "ended";
          livekit_room_name?: string | null;
          radio_output_active?: boolean;
          thumbnail_url?: string | null;
          scheduled_at?: string | null;
          started_at?: string | null;
          ended_at?: string | null;
          recording_url?: string | null;
        };
      };
      platikas_messages: {
        Row: {
          id: string;
          pláticas_id: string;
          user_id: string;
          content: string;
          is_moderated: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          pláticas_id: string;
          user_id: string;
          content: string;
          is_moderated?: boolean;
          created_at?: string;
        };
        Update: {
          content?: string;
          is_moderated?: boolean;
        };
      };
      platikas_requests: {
        Row: {
          id: string;
          pláticas_id: string;
          user_id: string;
          status: "pending" | "approved" | "rejected" | "completed";
          message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          pláticas_id: string;
          user_id: string;
          status?: "pending" | "approved" | "rejected" | "completed";
          message?: string | null;
          created_at?: string;
        };
        Update: {
          status?: "pending" | "approved" | "rejected" | "completed";
        };
      };
      question_sets: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          created_by: string;
          is_public: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          created_by: string;
          is_public?: boolean;
          created_at?: string;
        };
        Update: {
          title?: string;
          description?: string | null;
          is_public?: boolean;
        };
      };
      questions: {
        Row: {
          id: string;
          question_set_id: string;
          question_text: string;
          option_a: string;
          option_b: string;
          option_c: string;
          option_d: string;
          correct_option: "a" | "b" | "c" | "d";
          bible_reference: string | null;
          time_limit_seconds: number;
          points: number;
          order_index: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          question_set_id: string;
          question_text: string;
          option_a: string;
          option_b: string;
          option_c: string;
          option_d: string;
          correct_option: "a" | "b" | "c" | "d";
          bible_reference?: string | null;
          time_limit_seconds?: number;
          points?: number;
          order_index?: number;
          created_at?: string;
        };
        Update: {
          question_text?: string;
          option_a?: string;
          option_b?: string;
          option_c?: string;
          option_d?: string;
          correct_option?: "a" | "b" | "c" | "d";
          bible_reference?: string | null;
          time_limit_seconds?: number;
          points?: number;
          order_index?: number;
        };
      };
      games: {
        Row: {
          id: string;
          title: string;
          host_id: string;
          question_set_id: string;
          status: "lobby" | "in_progress" | "finished";
          current_question_index: number;
          join_code: string;
          started_at: string | null;
          finished_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          host_id: string;
          question_set_id: string;
          status?: "lobby" | "in_progress" | "finished";
          current_question_index?: number;
          join_code: string;
          started_at?: string | null;
          finished_at?: string | null;
          created_at?: string;
        };
        Update: {
          title?: string;
          status?: "lobby" | "in_progress" | "finished";
          current_question_index?: number;
          started_at?: string | null;
          finished_at?: string | null;
        };
      };
      game_teams: {
        Row: {
          id: string;
          game_id: string;
          name: string;
          color: string;
          score: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          game_id: string;
          name: string;
          color?: string;
          score?: number;
          created_at?: string;
        };
        Update: {
          name?: string;
          color?: string;
          score?: number;
        };
      };
      game_players: {
        Row: {
          id: string;
          game_id: string;
          team_id: string | null;
          user_id: string;
          score: number;
          joined_at: string;
        };
        Insert: {
          id?: string;
          game_id: string;
          team_id?: string | null;
          user_id: string;
          score?: number;
          joined_at?: string;
        };
        Update: {
          team_id?: string | null;
          score?: number;
        };
      };
      game_answers: {
        Row: {
          id: string;
          game_id: string;
          question_id: string;
          player_id: string;
          selected_option: "a" | "b" | "c" | "d";
          is_correct: boolean;
          time_taken_ms: number;
          answered_at: string;
        };
        Insert: {
          id?: string;
          game_id: string;
          question_id: string;
          player_id: string;
          selected_option: "a" | "b" | "c" | "d";
          is_correct: boolean;
          time_taken_ms: number;
          answered_at?: string;
        };
        Update: Record<string, never>;
      };
      archive: {
        Row: {
          id: string;
          pláticas_id: string | null;
          title: string;
          description: string | null;
          recording_url: string;
          thumbnail_url: string | null;
          duration_seconds: number | null;
          category_id: string | null;
          tags: string[];
          view_count: number;
          is_published: boolean;
          published_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          pláticas_id?: string | null;
          title: string;
          description?: string | null;
          recording_url: string;
          thumbnail_url?: string | null;
          duration_seconds?: number | null;
          category_id?: string | null;
          tags?: string[];
          view_count?: number;
          is_published?: boolean;
          published_at?: string | null;
          created_at?: string;
        };
        Update: {
          title?: string;
          description?: string | null;
          recording_url?: string;
          thumbnail_url?: string | null;
          duration_seconds?: number | null;
          category_id?: string | null;
          tags?: string[];
          view_count?: number;
          is_published?: boolean;
          published_at?: string | null;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
