-- ============================================================
-- Elim LLDM — Palabra del Día: banco inicial (149 palabras)
--
-- GENERADO por scripts/palabra/generar-seed.mjs desde
-- scripts/palabra/palabras-seed.mjs — no editar a mano; cambia la fuente,
-- regenera y corre scripts/palabra/verificar-seed.mjs.
--
-- Asigna una palabra por día empezando HOY en America/Los_Angeles (la
-- misma zona que PALABRA_TZ en src/lib/palabra/config.ts), es decir, el
-- día en que se aplique esta migración. ON CONFLICT: si alguna fecha ya
-- tiene palabra (p. ej. agregada desde /admin/palabra), se respeta.
-- ============================================================

WITH hoy AS (
  SELECT (NOW() AT TIME ZONE 'America/Los_Angeles')::DATE AS d
)
INSERT INTO palabra_diaria (fecha, palabra, explicacion, referencia)
SELECT hoy.d + (v.orden - 1), v.palabra, v.explicacion, v.referencia
FROM hoy, (VALUES
  (1, 'JESÚS', 'Nombre del Hijo de Dios; significa "Dios salva".', 'Mateo 1:21'),
  (2, 'SALMO', 'Canto de alabanza; David los escribió en el libro de los Salmos.', 'Lucas 20:42'),
  (3, 'MARÍA', 'Madre de Jesús, a quien el ángel Gabriel visitó en Nazaret.', 'Lucas 1:30'),
  (4, 'TORRE', 'Los hombres quisieron edificar una torre que llegara al cielo en Babel.', 'Génesis 11:4'),
  (5, 'MONTE', 'Desde un monte Jesús enseñó las bienaventuranzas.', 'Mateo 5:1'),
  (6, 'REINO', 'Jesús enseñó a buscar primeramente el reino de Dios y su justicia.', 'Mateo 6:33'),
  (7, 'ALTAR', 'Noé edificó un altar al Señor al salir del arca.', 'Génesis 8:20'),
  (8, 'PALMA', 'Recibieron a Jesús en Jerusalén con ramas de palmera.', 'Juan 12:13'),
  (9, 'ÁNGEL', 'El ángel Gabriel fue enviado por Dios a Nazaret.', 'Lucas 1:26'),
  (10, 'LIRIO', 'Jesús invitó a considerar los lirios del campo, que no se afanan.', 'Mateo 6:28'),
  (11, 'PEDRO', 'Apóstol a quien Jesús llamó roca.', 'Mateo 16:18'),
  (12, 'PABLO', 'Apóstol de los gentiles, antes llamado Saulo.', 'Hechos 13:9'),
  (13, 'MATEO', 'Publicano que dejó todo para seguir a Jesús.', 'Mateo 9:9'),
  (14, 'JUDAS', 'Discípulo que entregó a Jesús por treinta piezas de plata.', 'Mateo 26:15'),
  (15, 'TOMÁS', 'Discípulo que creyó al ver las heridas de Jesús resucitado.', 'Juan 20:27'),
  (16, 'MARTA', 'Hermana de Lázaro, afanada en muchos quehaceres.', 'Lucas 10:41'),
  (17, 'BELÉN', 'Ciudad de Judea donde nació Jesús.', 'Mateo 2:1'),
  (18, 'SIMÓN', 'Hombre de Cirene obligado a llevar la cruz de Jesús.', 'Marcos 15:21'),
  (19, 'JACOB', 'Soñó con una escalera que llegaba al cielo.', 'Génesis 28:12'),
  (20, 'ISAAC', 'Hijo de la promesa de Abraham y Sara.', 'Génesis 22:2'),
  (21, 'DAVID', 'Pastor ungido como rey de Israel.', '1 Samuel 16:13'),
  (22, 'AARÓN', 'Hermano de Moisés que habló por él ante Faraón.', 'Éxodo 4:14'),
  (23, 'JONÁS', 'Profeta que estuvo tres días en el vientre de un gran pez.', 'Jonás 1:17'),
  (24, 'NOEMÍ', 'Suegra de Rut, a quien Rut decidió seguir.', 'Rut 1:16'),
  (25, 'CALEB', 'Siguió al Señor con integridad y entró a la tierra prometida.', 'Números 14:24'),
  (26, 'ELÍAS', 'Profeta llevado al cielo en un torbellino.', '2 Reyes 2:11'),
  (27, 'NAHÚM', 'Profeta que anunció la caída de Nínive.', 'Nahúm 1:1'),
  (28, 'LUCAS', 'El médico amado, compañero de Pablo.', 'Colosenses 4:14'),
  (29, 'SILAS', 'Cantaba himnos con Pablo en la cárcel a medianoche.', 'Hechos 16:25'),
  (30, 'FÉLIX', 'Gobernador que escuchó a Pablo hablar de la fe en Cristo.', 'Hechos 24:24'),
  (31, 'ESTER', 'Reina que intercedió por su pueblo ante el rey.', 'Ester 4:14'),
  (32, 'JAIRO', 'Principal de la sinagoga cuya hija Jesús levantó.', 'Marcos 5:22'),
  (33, 'SARAÍ', 'Esposa de Abram, a quien Dios llamó Sara.', 'Génesis 17:15'),
  (34, 'LABÁN', 'Padre de Lea y Raquel, tío de Jacob.', 'Génesis 29:16'),
  (35, 'JETRO', 'Suegro de Moisés que le aconsejó repartir el trabajo.', 'Éxodo 18:17'),
  (36, 'JOSUÉ', 'Sucesor de Moisés; Dios le pidió ser valiente.', 'Josué 1:9'),
  (37, 'NATÁN', 'Profeta que confrontó a David con una parábola.', '2 Samuel 12:7'),
  (38, 'URÍAS', 'Soldado fiel, esposo de Betsabé.', '2 Samuel 11:15'),
  (39, 'ÉFESO', 'Ciudad donde Pablo enseñó y que recibió una epístola.', 'Hechos 19:1'),
  (40, 'SIDÓN', 'Ciudad de la costa junto a Tiro, visitada por Jesús.', 'Mateo 15:21'),
  (41, 'SINAÍ', 'Monte donde Dios descendió para dar la ley.', 'Éxodo 19:20'),
  (42, 'HOREB', 'Monte de Dios donde Moisés vio la zarza ardiente.', 'Éxodo 3:1'),
  (43, 'BABEL', 'Lugar donde Dios confundió el lenguaje de toda la tierra.', 'Génesis 11:9'),
  (44, 'EMAÚS', 'Aldea hacia la cual caminaban dos discípulos con Jesús resucitado.', 'Lucas 24:13'),
  (45, 'GOSÉN', 'Tierra de Egipto donde habitó la familia de Jacob.', 'Génesis 47:6'),
  (46, 'SANTO', 'Los serafines proclamaban: santo, santo, santo.', 'Isaías 6:3'),
  (47, 'CIELO', 'En el principio creó Dios los cielos y la tierra.', 'Génesis 1:1'),
  (48, 'PODER', 'Los discípulos recibirían poder del Espíritu Santo.', 'Hechos 1:8'),
  (49, 'VERBO', 'En el principio era el Verbo, y el Verbo era Dios.', 'Juan 1:1'),
  (50, 'FRUTO', 'El fruto del Espíritu es amor, gozo, paz…', 'Gálatas 5:22'),
  (51, 'JUSTO', 'El justo por la fe vivirá.', 'Romanos 1:17'),
  (52, 'MANSO', 'Jesús dijo ser manso y humilde de corazón.', 'Mateo 11:29'),
  (53, 'AYUNO', 'Dios describe el ayuno que a Él le agrada.', 'Isaías 58:6'),
  (54, 'MUNDO', 'De tal manera amó Dios al mundo.', 'Juan 3:16'),
  (55, 'FUEGO', 'Lenguas como de fuego se posaron sobre los discípulos.', 'Hechos 2:3'),
  (56, 'PANES', 'Un muchacho tenía cinco panes de cebada.', 'Juan 6:9'),
  (57, 'PECES', 'Con dos peces y cinco panes Jesús alimentó a la multitud.', 'Mateo 14:17'),
  (58, 'TRIGO', 'Si el grano de trigo no muere, queda solo.', 'Juan 12:24'),
  (59, 'GRANO', 'El reino de los cielos es semejante al grano de mostaza.', 'Mateo 13:31'),
  (60, 'LECHE', 'Una tierra que fluye leche y miel.', 'Éxodo 3:8'),
  (61, 'CETRO', 'No será quitado el cetro de Judá.', 'Génesis 49:10'),
  (62, 'TRONO', 'Juan vio un trono establecido en el cielo.', 'Apocalipsis 4:2'),
  (63, 'ATRIO', 'Mejor es un día en los atrios de Dios que mil fuera de ellos.', 'Salmos 84:10'),
  (64, 'SELLO', 'Un libro sellado con siete sellos.', 'Apocalipsis 5:1'),
  (65, 'LIBRO', 'Los muertos fueron juzgados según lo escrito en los libros.', 'Apocalipsis 20:12'),
  (66, 'ROLLO', 'Dios mandó a Ezequiel comer el rollo.', 'Ezequiel 3:1'),
  (67, 'TABLA', 'Dios dio a Moisés dos tablas del testimonio.', 'Éxodo 31:18'),
  (68, 'OVEJA', 'El pastor deja las noventa y nueve por la oveja perdida.', 'Lucas 15:4'),
  (69, 'REDIL', 'Jesús tiene otras ovejas que no son de este redil.', 'Juan 10:16'),
  (70, 'LOBOS', 'Falsos profetas vestidos de ovejas, por dentro lobos.', 'Mateo 7:15'),
  (71, 'VIUDA', 'Una viuda pobre echó dos blancas en la ofrenda.', 'Marcos 12:42'),
  (72, 'NIÑOS', 'Dejad a los niños venir a mí.', 'Marcos 10:14'),
  (73, 'SEÑOR', 'Toda lengua confesará que Jesucristo es el Señor.', 'Filipenses 2:11'),
  (74, 'SUEÑO', 'José tuvo un sueño y lo contó a sus hermanos.', 'Génesis 37:5'),
  (75, 'MAGOS', 'Sabios que vinieron del oriente a adorar al niño.', 'Mateo 2:1'),
  (76, 'MIRRA', 'Uno de los regalos que los magos ofrecieron a Jesús.', 'Mateo 2:11'),
  (77, 'SABIO', 'Da al sabio, y será más sabio.', 'Proverbios 9:9'),
  (78, 'NECIO', 'El camino del necio es derecho en su opinión.', 'Proverbios 12:15'),
  (79, 'BODAS', 'En unas bodas en Caná Jesús hizo su primera señal.', 'Juan 2:1'),
  (80, 'MADRE', 'Desde la cruz Jesús dijo: "He ahí tu madre".', 'Juan 19:27'),
  (81, 'PADRE', 'Padre nuestro que estás en los cielos.', 'Mateo 6:9'),
  (82, 'TRIBU', 'El León de la tribu de Judá ha vencido.', 'Apocalipsis 5:5'),
  (83, 'SIETE', 'Perdonar hasta setenta veces siete.', 'Mateo 18:22'),
  (84, 'NUBES', 'Verán al Hijo del Hombre venir en las nubes.', 'Marcos 13:26'),
  (85, 'BARCA', 'Jesús dormía en la barca durante la tempestad.', 'Mateo 8:24'),
  (86, 'REDES', 'Jesús mandó a Simón echar las redes para pescar.', 'Lucas 5:4'),
  (87, 'LLAVE', 'El que tiene la llave de David abre y nadie cierra.', 'Apocalipsis 3:7'),
  (88, 'HONDA', 'Con una honda y una piedra David venció al gigante.', '1 Samuel 17:50'),
  (89, 'LANZA', 'Un soldado abrió el costado de Jesús con una lanza.', 'Juan 19:34'),
  (90, 'YELMO', 'Tomad el yelmo de la salvación.', 'Efesios 6:17'),
  (91, 'CARNE', 'El Verbo se hizo carne y habitó entre nosotros.', 'Juan 1:14'),
  (92, 'POLVO', 'Polvo eres, y al polvo volverás.', 'Génesis 3:19'),
  (93, 'MANTO', 'Eliseo tomó el manto que se le cayó a Elías.', '2 Reyes 2:13'),
  (94, 'HIGOS', '¿Acaso se recogen higos de los abrojos?', 'Mateo 7:16'),
  (95, 'OLIVO', 'Las ramas injertadas en el buen olivo.', 'Romanos 11:17'),
  (96, 'CEDRO', 'El justo crecerá como cedro en el Líbano.', 'Salmos 92:12'),
  (97, 'ÁRBOL', 'En medio del huerto, el árbol de vida.', 'Génesis 2:9'),
  (98, 'ARENA', 'El hombre insensato edificó su casa sobre la arena.', 'Mateo 7:26'),
  (99, 'VALLE', 'Aunque ande en valle de sombra de muerte, no temeré.', 'Salmos 23:4'),
  (100, 'MUROS', 'Por la fe cayeron los muros de Jericó.', 'Hebreos 11:30'),
  (101, 'TECHO', 'Descubrieron el techo para bajar al paralítico.', 'Marcos 2:4'),
  (102, 'HORNO', 'Echaron a tres jóvenes en el horno de fuego ardiendo.', 'Daniel 3:20'),
  (103, 'SEÑAL', 'La virgen concebirá: la señal que Dios mismo daría.', 'Isaías 7:14'),
  (104, 'HIMNO', 'Después de cantar el himno, salieron al monte de los Olivos.', 'Mateo 26:30'),
  (105, 'ÉXODO', 'Salida del pueblo de Israel de la tierra de Egipto.', 'Éxodo 12:41'),
  (106, 'HAGEO', 'Profeta que animó a reedificar la casa de Dios.', 'Hageo 1:1'),
  (107, 'OSEAS', 'Profeta que habló del amor fiel de Dios por su pueblo.', 'Oseas 1:1'),
  (108, 'JUDÍO', 'El evangelio es poder de Dios al judío primeramente.', 'Romanos 1:16'),
  (109, 'OMEGA', 'Yo soy el Alfa y la Omega, dice el Señor.', 'Apocalipsis 1:8'),
  (110, 'CIEGO', 'Jesús vio a un hombre ciego de nacimiento.', 'Juan 9:1'),
  (111, 'SORDO', 'Le trajeron a Jesús un sordo y tartamudo.', 'Marcos 7:32'),
  (112, 'LEPRA', 'Jesús tocó al leproso y su lepra desapareció.', 'Mateo 8:3'),
  (113, 'PERLA', 'El mercader que vendió todo por una perla preciosa.', 'Mateo 13:46'),
  (114, 'DEUDA', 'El señor, movido a misericordia, le perdonó la deuda.', 'Mateo 18:27'),
  (115, 'SIEGA', 'Los campos ya están blancos para la siega.', 'Juan 4:35'),
  (116, 'ARADO', 'Nadie que mira atrás después de poner la mano en el arado.', 'Lucas 9:62'),
  (117, 'CARGA', 'Mi yugo es fácil, y ligera mi carga.', 'Mateo 11:30'),
  (118, 'OBRAS', 'La fe sin obras está muerta.', 'Santiago 2:26'),
  (119, 'DONES', 'Hay diversidad de dones, pero el Espíritu es el mismo.', '1 Corintios 12:4'),
  (120, 'NARDO', 'María ungió los pies de Jesús con perfume de nardo puro.', 'Juan 12:3'),
  (121, 'SALVO', 'Todo aquel que invocare el nombre del Señor será salvo.', 'Romanos 10:13'),
  (122, 'LIBRE', 'Si el Hijo os libertare, seréis verdaderamente libres.', 'Juan 8:36'),
  (123, 'AMADO', 'Voz del cielo: "Este es mi Hijo amado".', 'Mateo 3:17'),
  (124, 'TEMOR', 'El principio de la sabiduría es el temor del Señor.', 'Proverbios 1:7'),
  (125, 'NUEVO', 'Un mandamiento nuevo os doy: que os améis unos a otros.', 'Juan 13:34'),
  (126, 'BUENO', 'Dios vio todo lo que había hecho, y era bueno en gran manera.', 'Génesis 1:31'),
  (127, 'AGUAS', 'El Espíritu de Dios se movía sobre la faz de las aguas.', 'Génesis 1:2'),
  (128, 'ROCÍO', 'Isaac bendijo a Jacob con el rocío del cielo.', 'Génesis 27:28'),
  (129, 'CAMPO', 'El reino es como un tesoro escondido en un campo.', 'Mateo 13:44'),
  (130, 'AGUJA', 'Es más fácil pasar un camello por el ojo de una aguja.', 'Mateo 19:24'),
  (131, 'BARRO', 'Como el barro en la mano del alfarero, así es Israel en la mano de Dios.', 'Jeremías 18:6'),
  (132, 'VELAD', 'Jesús pidió a sus discípulos: velad y orad.', 'Mateo 26:41'),
  (133, 'JUDEA', 'Testigos en Jerusalén, en toda Judea, en Samaria y hasta lo último de la tierra.', 'Hechos 1:8'),
  (134, 'TARSO', 'Ciudad natal de Saulo, el que después fue Pablo.', 'Hechos 9:11'),
  (135, 'CRETA', 'Isla donde Pablo dejó a Tito para poner en orden la iglesia.', 'Tito 1:5'),
  (136, 'MALTA', 'Isla donde Pablo llegó tras naufragar.', 'Hechos 28:1'),
  (137, 'SIRIA', 'Cirenio era gobernador de Siria cuando nació Jesús.', 'Lucas 2:2'),
  (138, 'SALEM', 'Melquisedec era rey de Salem y sacerdote del Dios Altísimo.', 'Hebreos 7:1'),
  (139, 'RAHAB', 'Mujer de Jericó que escondió a los espías de Israel.', 'Josué 2:1'),
  (140, 'JAFET', 'Uno de los tres hijos de Noé.', 'Génesis 9:18'),
  (141, 'RUBÉN', 'Hermano mayor que libró a José de la muerte.', 'Génesis 37:21'),
  (142, 'LIDIA', 'Vendedora de púrpura cuyo corazón abrió el Señor.', 'Hechos 16:14'),
  (143, 'DEMAS', 'Colaborador de Pablo que lo desamparó amando este mundo.', '2 Timoteo 4:10'),
  (144, 'LOIDA', 'Abuela de Timoteo, de fe no fingida.', '2 Timoteo 1:5'),
  (145, 'JUANA', 'Mujer que servía a Jesús con sus bienes.', 'Lucas 8:3'),
  (146, 'CÉSAR', 'Dad a César lo que es de César, y a Dios lo que es de Dios.', 'Mateo 22:21'),
  (147, 'MALCO', 'Siervo del sumo sacerdote a quien Pedro cortó la oreja.', 'Juan 18:10'),
  (148, 'SAULO', 'Jesús le preguntó en el camino: ¿por qué me persigues?', 'Hechos 9:4'),
  (149, 'TADEO', 'Uno de los doce apóstoles.', 'Mateo 10:3')
) AS v(orden, palabra, explicacion, referencia)
ON CONFLICT (fecha) DO NOTHING;
